version: '3.8'

services:
  mongodb:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data: